<?php
ob_start(); 
include "main.php";
require_once('dbconnect.php');

// set_time_limit(100);
// ini_set('display_errors', '1');
// ini_set('display_startup_errors', '1');
// error_reporting(E_ALL);
ini_set('MAX_EXECUTION_TIME', 3600);
use simitsdk\phpjasperxml\PHPJasperXML;

$filename = __DIR__.'/HighRecPayreport.jrxml';

$data = [];
$faker = Faker\Factory::create('en_US');

// $conn = pg_connect("host=127.0.0.1 dbname=hrdatabase user=postgres password=tushar");

// variables
$START_DATE = $_GET['START_DATE'];
$END_DATE = $_GET['END_DATE'];
$BRANCH = $_GET['BRANCH'];
$AC_TYPE = $_GET['AC_TYPE'];
$BANK_NAME = $_GET['BANK_NAME'];
$BRANCH_CODE = $_GET['BRANCH_CODE'];
$TRAN_STATUS = '1';
$T1 = " || ' ' ||";




$START_DATE1 = str_replace("'", "" , $START_DATE);
$END_DATE2 = str_replace("'", "" , $END_DATE);
$BRANCH = str_replace("'", "" , $BRANCH);
$AC_TYPE = str_replace("'", "" , $AC_TYPE );
$BANK_NAME = str_replace("'", "" , $BANK_NAME);

$schemecode = "'SB'";
$ac_type ="'8'";
$dateformat ="'DD/MM/YYYY'";





    $query = ' SELECT TRANTABLE,*, ( SELECT "AC_NAME" FROM DPMASTER WHERE DPMASTER."AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND DPMASTER."AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER)
    AND "BANKACNO" = "TRAN_ACNO"  UNION ALL  SELECT "AC_NAME" FROM LNMASTER 
    WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER)  AND "BANKACNO" = "TRAN_ACNO" 
             UNION ALL 
    SELECT "AC_NAME" FROM PGMASTER  WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) 
    AND "BANKACNO" = "TRAN_ACNO" ) AC_NAME,
    (SELECT SCHEMAST."S_NAME"
		FROM SCHEMAST
		WHERE SCHEMAST.ID = CAST("TRAN_ACTYPE" AS INTEGER)
 ) S_NAME,
  
  ( SELECT  "AC_OPDATE"  FROM DPMASTER WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) 
                       AND "BANKACNO" = "TRAN_ACNO" UNION ALL 
   SELECT "AC_OPDATE" FROM LNMASTER WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND "BANKACNO" = "TRAN_ACNO" 
             UNION ALL SELECT "AC_OPDATE" FROM PGMASTER WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) 
                       AND "BANKACNO" = "TRAN_ACNO" ) AC_OPDATE,
  
   ( SELECT IDMASTER."AC_PANNO" FROM DPMASTER,IDMASTER WHERE DPMASTER."AC_ACNOTYPE" = "TRAN_ACNOTYPE" 
                        AND DPMASTER."AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND DPMASTER."BANKACNO" = "TRAN_ACNO"
                        AND DPMASTER."AC_CUSTID" = IDMASTER."AC_NO" 
             UNION ALL 
   SELECT IDMASTER."AC_PANNO" FROM LNMASTER,IDMASTER WHERE LNMASTER."AC_ACNOTYPE" = "TRAN_ACNOTYPE"
          AND LNMASTER."AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND LNMASTER."BANKACNO" = "TRAN_ACNO" AND LNMASTER."AC_CUSTID" = IDMASTER."AC_NO" 
       UNION ALL SELECT IDMASTER."AC_PANNO" FROM PGMASTER,IDMASTER WHERE PGMASTER."AC_ACNOTYPE" = "TRAN_ACNOTYPE" 
      AND PGMASTER."AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND PGMASTER."BANKACNO" = "TRAN_ACNO" AND PGMASTER."AC_CUSTID" = IDMASTER."AC_NO" ) AC_PANNO ,
  
  ( SELECT "AC_WARD" '.$T1.' "AC_ADDR" '.$T1.' "AC_GALLI" '.$T1.' CITYMASTER."CITY_NAME" AC_ADDRESS 
                        FROM DPMASTER 
                        LEFT OUTER JOIN CUSTOMERADDRESS ON CUSTOMERADDRESS."idmasterID" = DPMASTER."idmasterID"
                        LEFT OUTER JOIN CITYMASTER ON CUSTOMERADDRESS."AC_CTCODE" = CITYMASTER.id
                        WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = cast("TRAN_ACTYPE" as integer) AND "BANKACNO" = "TRAN_ACNO" 	  
             UNION ALL 
   SELECT "AC_WARD" '.$T1.' "AC_ADDR" '.$T1.' "AC_GALLI" '.$T1.' CITYMASTER."CITY_NAME" AC_ADDRESS 
                        FROM LNMASTER 
                         LEFT OUTER JOIN CUSTOMERADDRESS ON CUSTOMERADDRESS."idmasterID" = LNMASTER."idmasterID"
                        LEFT OUTER JOIN CITYMASTER ON CUSTOMERADDRESS."AC_CTCODE" = CITYMASTER.id
  WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND "BANKACNO" = "TRAN_ACNO" 
                        AND CUSTOMERADDRESS."AC_CTCODE" = CITYMASTER.id 
             UNION ALL
  SELECT "AC_WARD" '.$T1.' "AC_ADDR" '.$T1.' "AC_GALLI" '.$T1.' CITYMASTER."CITY_NAME" AC_ADDRESS 
    FROM PGMASTER
           LEFT OUTER JOIN CUSTOMERADDRESS ON CUSTOMERADDRESS."idmasterID" = PGMASTER."idmasterID"
          LEFT OUTER JOIN CITYMASTER ON CUSTOMERADDRESS."AC_CTCODE" = CITYMASTER.id
                       WHERE "AC_ACNOTYPE" = "TRAN_ACNOTYPE" AND "AC_TYPE" = CAST("TRAN_ACTYPE" AS INTEGER) AND "BANKACNO" = "TRAN_ACNO"
                        AND CUSTOMERADDRESS."AC_CTCODE" = CITYMASTER."CITY_CODE" ) AC_ADDRESS
  FROM(
  SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("TRAN_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN
                WHERE  CAST("TRAN_AMOUNT" AS FLOAT) >= 25000 And CAST("TRAN_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE ) >= ('.$END_DATE.') 
                AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.'
                UNION ALL 							
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("INTEREST_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  CAST("INTEREST_AMOUNT" AS INTEGER) >= 25000 And CAST("INTEREST_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("PENAL_INTEREST" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  CAST("PENAL_INTEREST" AS FLOAT) >= 25000 And CAST("PENAL_INTEREST" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "RECPAY_INT_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "RECPAY_INT_AMOUNT" >= 25000 And "RECPAY_INT_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER1_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER1_AMOUNT" >= 25000 And "OTHER1_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER2_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER2_AMOUNT" >= 25000 And "OTHER2_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER3_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER3_AMOUNT" >= 25000 And "OTHER3_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER4_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER4_AMOUNT" >= 25000 And "OTHER4_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER5_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER5_AMOUNT" >= 25000 And "OTHER5_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER6_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER6_AMOUNT" >= 25000 And "OTHER6_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER7_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER7_AMOUNT" >= 25000 And "OTHER7_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER8_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER8_AMOUNT" >= 25000 And "OTHER8_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER9_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER9_AMOUNT" >= 25000 And "OTHER9_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER10_AMOUNT" TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER10_AMOUNT" >= 25000 And "OTHER10_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("ADDED_PENAL_INTEREST" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  CAST("ADDED_PENAL_INTEREST" AS FLOAT) >= 25000 And CAST("ADDED_PENAL_INTEREST" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) >= 25000 And CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("OTHER11_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  "OTHER11_AMOUNT" >= 25000 And "OTHER11_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("TRAN_AMOUNT" AS FLOAT)  TRAN_AMOUNT 
                FROM DEPOTRAN WHERE  CAST("TRAN_AMOUNT" AS FLOAT) >= 25000 And CAST("TRAN_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("TRAN_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("TRAN_AMOUNT" AS FLOAT) >= 25000 And CAST("TRAN_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("PENAL_INTEREST" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("PENAL_INTEREST" AS FLOAT) >= 25000 And CAST("PENAL_INTEREST" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("RECPAY_INT_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("RECPAY_INT_AMOUNT" AS FLOAT) >= 25000 And CAST("RECPAY_INT_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL
               SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("INTEREST_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("INTEREST_AMOUNT" AS FLOAT) >= 25000 And CAST("INTEREST_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER1_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER1_AMOUNT" >= 25000 And "OTHER1_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER2_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER2_AMOUNT" >= 25000 And "OTHER2_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER3_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER3_AMOUNT" >= 25000 And "OTHER3_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER4_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER4_AMOUNT" >= 25000 And "OTHER4_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <=('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER5_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER5_AMOUNT" >= 25000 And "OTHER5_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER6_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER6_AMOUNT" >= 25000 And "OTHER6_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER7_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER7_AMOUNT" >= 25000 And "OTHER7_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER8_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER8_AMOUNT" >= 25000 And "OTHER8_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER9_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER9_AMOUNT" >= 25000 And "OTHER9_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER10_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER10_AMOUNT" >= 25000 And "OTHER10_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("ADDED_PENAL_INTEREST" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("ADDED_PENAL_INTEREST" AS FLOAT) >= 25000 And CAST("ADDED_PENAL_INTEREST" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM LOANTRAN WHERE  CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) >= 25000 And CAST("REC_PENAL_INT_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE"  , "TRAN_DRCR" , "OTHER11_AMOUNT" TRAN_AMOUNT 
                FROM LOANTRAN WHERE  "OTHER11_AMOUNT" >= 25000 And "OTHER11_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("TRAN_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  CAST("TRAN_AMOUNT" AS FLOAT) >= 25000 And CAST("TRAN_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("INTEREST_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  CAST("INTEREST_AMOUNT" AS FLOAT) >= 25000 And CAST("INTEREST_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , CAST("RECPAY_INT_AMOUNT" AS FLOAT) TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  CAST("RECPAY_INT_AMOUNT" AS FLOAT) >= 25000 And CAST("RECPAY_INT_AMOUNT" AS FLOAT) <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER1_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER1_AMOUNT" >= 25000 And "OTHER1_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER2_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER2_AMOUNT" >= 25000 And "OTHER2_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER3_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER3_AMOUNT" >= 25000 And "OTHER3_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER4_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER4_AMOUNT" >= 25000 And "OTHER4_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER5_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER5_AMOUNT" >= 25000 And "OTHER5_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER6_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER6_AMOUNT" >= 25000 And "OTHER6_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER7_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER7_AMOUNT" >= 25000 And "OTHER7_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER8_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER8_AMOUNT" >= 25000 And "OTHER8_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER9_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER9_AMOUNT" >= 25000 And "OTHER9_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER10_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER10_AMOUNT" >= 25000 And "OTHER10_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.') AND "BRANCH_CODE"='.$BRANCH_CODE.' UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE" , "TRAN_DRCR" , "OTHER11_AMOUNT" TRAN_AMOUNT 
                FROM PIGMYTRAN WHERE  "OTHER11_AMOUNT" >= 25000 And "OTHER11_AMOUNT" <= 9999999.99 AND CAST("TRAN_DATE" AS DATE) >= ('.$END_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.')  AND "BRANCH_CODE"='.$BRANCH_CODE.'
                UNION ALL 
                SELECT "TRAN_ACNOTYPE" , "TRAN_ACTYPE" , "TRAN_ACNO" , "TRAN_DATE"  , "TRAN_DRCR" , "TRAN_AMOUNT" 
                FROM VWDETAILDAILYTRAN WHERE CAST("TRAN_STATUS" AS INTEGER) = '.$TRAN_STATUS.'  and "BRANCH_CODE"='.$BRANCH_CODE.' AND 
                 CAST("TRAN_AMOUNT" AS FLOAT) >= 25000 AND CAST("TRAN_AMOUNT" AS FLOAT) <= 9999999.99 
                AND CAST("TRAN_DATE" AS DATE) >= ('.$START_DATE.') AND CAST("TRAN_DATE" AS DATE) <= ('.$END_DATE.')) TRANTABLE';
             

                //  echo $query;

             
$sql =  pg_query($conn,$query);

 $i = 0;

while($row = pg_fetch_assoc($sql))
{ 
    
    $tmp=[
        'ac_name' => $row['ac_name'],
        'ac_panno' => $row['ac_panno'],
        'ac_opdate' => $row['ac_opdate'],
        'ac_address' => $row['ac_address'],
        'TRAN_DATE' => $row['TRAN_DATE'],
        'tran_amount' => $row['tran_amount'],
        'START_DATE' => $START_DATE1,
        'END_DATE'  => $END_DATE2,
        'BRANCH'  => $BRANCH,
        'AC_TYPE' => $AC_TYPE,
        'S_NAME' => $row['s_name'],
        'BANK_NAME' => $BANK_NAME,
         
    ];
    $data[$i]=$tmp;
    $i++;  
}
ob_end_clean();
// echo $query;

$config = ['driver'=>'array','data'=>$data];
// echo $filename;
//print_r($data);
$report = new PHPJasperXML();
$report->load_xml_file($filename)    
    ->setDataSource($config)
    ->export('Pdf');
    
?>