<?php
ob_start(); 
include "main.php";
require_once('dbconnect.php');
// ini_set('display_errors', '1');
// ini_set('display_startup_errors', '1');
// error_reporting(E_ALL);
use simitsdk\phpjasperxml\PHPJasperXML;

$filename = __DIR__.'/OTHER_SUBSIDAIRY.jrxml';

$data = [];
$faker = Faker\Factory::create('en_US');

$bankName   = $_GET['bankname'];
$branchName = $_GET['Branch']; 
$stdate = $_GET['sdate'];
$edate = $_GET['edate'];
// $date = $_GET['date'];

// $failure = $_GET['failure'];
// $TRAN_PROCESS_MONTH = $_GET['TRAN_PROCESS_MONTH'];



$bankName1 = str_replace("'", "", $bankName);
$stdate_ = str_replace("'", "", $stdate);
$edate_ = str_replace("'", "", $edate);
// $startscheme = str_replace("'", "", $startscheme);
$branchName = str_replace("'","",$branchName);

$datefandmate = "'dd/mm/yyyy'";
// $dd="'DD/MM/YYYY'";

// $dd/mm/yyyy = "'DD/MM/YYYY'";
$c = "'C'"; 
$d = "'D'";
$jv = "'JV'";
$cs = "'CS'";
$tr = "'TR'";
$cl = "'CL'";
$TRAN_STATUS = "'1'";
$TRAN_AMOUNT = "'TRAN_AMOUNT'";
$INTEREST_AMOUNT = "'INTEREST_AMOUNT'";  
$no = "'98010'";
$RECPAY_INT_AMOUNT = "'RECPAY_INT_AMOUNT'"; 
$DD_COMMISSION_AMT = "'DD_COMMISSION_AMT'"; 
$PENAL_INT_AMOUNT = "'PENAL_INT_AMOUNT'"; 
$REC_PENAL_INT_AMOUNT = "'REC_PENAL_INT_AMOUNT'";
$OTHER1_AMOUNT = "'OTHER1_AMOUNT'"; 
$OTHER2_AMOUNT = "'OTHER2_AMOUNT'"; 
$OTHER3_AMOUNT = "'OTHER3_AMOUNT'"; 
$OTHER4_AMOUNT = "'OTHER4_AMOUNT'"; 
$OTHER5_AMOUNT = "'OTHER5_AMOUNT'"; 
$OTHER6_AMOUNT = "'OTHER6_AMOUNT'"; 
$OTHER7_AMOUNT = "'OTHER7_AMOUNT'"; 
$OTHER8_AMOUNT = "'OTHER8_AMOUNT'"; 
$OTHER9_AMOUNT = "'OTHER9_AMOUNT'"; 
$OTHER10_AMOUNT = "'OTHER10_AMOUNT'"; 
$OTHER11_AMOUNT = "'OTHER11_AMOUNT'"; 
$OTHER12_AMOUNT = "'OTHER12_AMOUNT'"; 
$OTHER13_AMOUNT = "'OTHER13_AMOUNT'"; 

$OTHER1_AMOUNT = "'OTHER1_AMOUNT'"; 
$DIVIDEND_ENTRY = "'DIVIDEND_ENTRY'";


$query='SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TYPE", "TRAN_DRCR", "TRAN_GLACNO" , "TRAN_ACNOTYPE" 
, "TRAN_ACTYPE","TRAN_ACNO","CHEQUE_NO","TRAN_AMOUNT","NARRATION", "USER_CODE", "OFFICER_CODE" , 
"AC_SUBSCODE" AS "SUBSIDARY_CODE" , 
(Case "TRAN_DRCR"  When '.$c.' Then  "CASHAMT"  Else 0 End) "CRCASHAMT"  
, (Case  "TRAN_DRCR"  When '.$c.'  Then "TRANSFERAMT"  Else 0 End) "CRTRANSFERAMT"  
, (Case  "TRAN_DRCR"  When '.$c.' Then  "CLEARINGAMT"  Else 0 End) "CRCLEARINGAMT"  
, (Case "TRAN_DRCR"  When '.$d.' Then  "CASHAMT"  Else 0 End) "DRCASHAMT"  
, (Case  "TRAN_DRCR"  When '.$d.' Then  "TRANSFERAMT"  Else 0 End) "DRTRANSFERAMT"  
, (Case  "TRAN_DRCR"  When '.$d.' Then  "CLEARINGAMT"  Else 0 End) "DRCLEARINGAMT" 
From 
(SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH","TRAN_ACTYPE" "TRAN_GLACTYPE", "TRAN_GLACNO", ACMASTER."AC_SUBSCODE","TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO", "TRAN_AMOUNT"
, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE"  , DAILYTRAN."TRAN_SOURCE_NO"  , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "TRAN_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.'THEN "TRAN_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CLEARINGAMT" , '.$TRAN_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."TRAN_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" ,"TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH","TRAN_ACTYPE" "TRAN_GLACTYPE", "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO", "TRAN_AMOUNT" , "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" ,  HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "TRAN_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "TRAN_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$TRAN_AMOUNT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON HISTORYTRAN."TRAN_GLACNO"= ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE","IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", "INTEREST_GLACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "INTEREST_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "INTEREST_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "INTEREST_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$INTEREST_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."INTEREST_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."INTEREST_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE",  "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", "INTEREST_GLACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "INTEREST_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "INTEREST_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "INTEREST_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$INTEREST_AMOUNT.' REF_FIELD  FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON HISTORYTRAN."INTEREST_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
AND HISTORYTRAN."INTEREST_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("RECPAY_INT_GLACNO" AS INTEGER) "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "RECPAY_INT_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$RECPAY_INT_AMOUNT.' REF_FILED  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."RECPAY_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND           
 DAILYTRAN."RECPAY_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All   
  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("RECPAY_INT_GLACNO" AS INTEGER) "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "RECPAY_INT_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$RECPAY_INT_AMOUNT.' REF_FILED  FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."RECPAY_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
  TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."RECPAY_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", 
"IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", "DD_COMMISSION_ACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "DD_COMMISSION_AMT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,DAILYTRAN."TRAN_SOURCE_NO" ,  DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CLEARINGAMT",'.$DD_COMMISSION_AMT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."DD_COMMISSION_ACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
AND DAILYTRAN."DD_COMMISSION_AMT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", "DD_COMMISSION_ACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO" , "DD_COMMISSION_AMT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CLEARINGAMT",'.$DD_COMMISSION_AMT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."DD_COMMISSION_ACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
 TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."DD_COMMISSION_AMT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", 
"PENAL_INT_GLACNO" AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , 
"PENAL_INT_AMOUNT" AS "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , 
DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$PENAL_INT_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
AND  DAILYTRAN."PENAL_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", 
 "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", 
 "PENAL_INT_GLACNO" AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  ,
 "PENAL_INT_AMOUNT" AS "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", 
 HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , 
 HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  ,
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$PENAL_INT_AMOUNT.' REF_FIELD  
FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO" 
WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."PENAL_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", 
"IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("REC_PENAL_INT_GLACNO" AS INTEGER) AS "TRAN_GLACNO", 
ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "REC_PENAL_INT_AMOUNT" AS TRAN_AMOUNT, "NARRATION", 
"TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , 
DAILYTRAN."TRAN_SOURCE_TYPE", DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  ,
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$REC_PENAL_INT_AMOUNT.' REF_FIELD  
FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."REC_PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  
WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= 
TO_DATE('.$edate.','.$datefandmate.')   AND  DAILYTRAN."REC_PENAL_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("REC_PENAL_INT_GLACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "REC_PENAL_INT_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO", HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$REC_PENAL_INT_AMOUNT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."REC_PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."REC_PENAL_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER1_ACNO" AS INTEGER)  AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE",
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER1_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER1_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER1_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER1_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER1_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND  DAILYTRAN."OTHER1_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
  "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER1_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
  "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER1_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
  HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
  HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , 
  COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER1_AMOUNT" ELSE 0 END,0)  + 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER1_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER1_AMOUNT.' REF_FIELD  
           FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER1_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
           WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
           AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
  AND HISTORYTRAN."OTHER1_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER2_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER2_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER2_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER2_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER2_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER2_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND  DAILYTRAN."OTHER2_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER2_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER2_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER2_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER2_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER2_AMOUNT.' REF_FIELD  
          FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER2_ACNO" AS INTEGER) = ACMASTER."AC_NO" 
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER2_AMOUNT" > 0   AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER3_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER3_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER",
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"     , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER3_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER3_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER3_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER3_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER3_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER3_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER3_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER3_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER3_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER3_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER3_ACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER3_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER4_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER4_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER4_AMOUNT" ELSE 0 END,0)  +
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER4_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER4_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER4_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER4_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER4_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER4_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" , 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE", HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER4_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER4_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CASHAMT" , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER4_AMOUNT.' REF_FIELD  
          FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER4_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER4_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER5_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER5_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" ,
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER5_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER5_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER5_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER5_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER5_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER5_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER5_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" , 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER5_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER5_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER5_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER5_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER5_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER6_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER6_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" ,
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   ,
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER6_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER6_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER6_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER6_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER6_AMOUNT" > 0 
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER6_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER6_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER6_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER6_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER6_AMOUNT.' REF_FIELD  
         FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER6_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
         AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
AND HISTORYTRAN."OTHER6_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER7_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER7_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
 DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER7_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER7_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER7_AMOUNT.' REF_FIELD  
          FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER7_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
          AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER7_AMOUNT" > 0 
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER7_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER7_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
 HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER7_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER7_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER7_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER7_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER7_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER8_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER8_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER8_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER8_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER8_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER8_ACNO" AS INTEGER) = ACMASTER."AC_NO" 
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER8_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER8_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER8_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER",
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER8_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER8_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER8_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER8_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER8_AMOUNT" > 0   AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER9_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE",
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER9_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  ,
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER9_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER9_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CLEARINGAMT" ,'.$OTHER9_AMOUNT.' REF_FIELD 
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER9_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER9_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER9_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER9_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER9_AMOUNT" ELSE 0 END,0)   + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER9_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER9_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER9_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER9_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER10_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER10_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER10_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER10_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER10_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER10_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER10_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER10_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER10_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER10_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER10_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  ,
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER10_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER10_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND 
          CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER10_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER11_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER11_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
 DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER11_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER11_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER11_AMOUNT.' REF_FIELD  
          FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER11_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
          AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
          AND DAILYTRAN."OTHER11_AMOUNT" > 0  
 AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER11_ACNO" AS INTEGER) AS "TRAN_GLACNO", 
 ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER11_AMOUNT" TRAN_AMOUNT, "NARRATION", 
 "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , 
 HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER11_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER11_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER11_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER11_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER11_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
) AS "VWTMPSUBSIDARYOTHER" 
  WHERE "DIVIDEND_ENTRY" <> true
  AND "TRAN_AMOUNT" <> 0  
  AND "AC_SUBSCODE" =2 
UNION ALL 
SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TYPE",  "TRAN_DRCR",  "TRAN_GLACNO" , "TRAN_ACNOTYPE" 
, "TRAN_ACTYPE" , CAST("TRAN_GLACNO" AS CHARACTER VARYING) AS "TRAN_ACNO", "CHEQUE_NO", "TRAN_AMOUNT" , '.$DIVIDEND_ENTRY.' "NARRATION",
"USER_CODE", "OFFICER_CODE" , "AC_SUBSCODE"  AS "SUBSIDARY_CODE" , Case "TRAN_DRCR" 
When '.$c.' Then  "CASHAMT"  Else 0 End "CRCASHAMT"  
, Case  "TRAN_DRCR"  When'.$c.'  Then "TRANSFERAMT"  Else 0 End "CRTRANSFERAMT"  
, Case  "TRAN_DRCR"  When '.$c.' Then  "CLEARINGAMT"  Else 0 End "CRCLEARINGAMT"  
, Case  "TRAN_DRCR"  When '.$d.' Then  "CASHAMT"  Else 0 End "DRCASHAMT"  
, Case  "TRAN_DRCR"  When '.$d.' Then  "TRANSFERAMT"  Else 0 End "DRTRANSFERAMT"  
, Case  "TRAN_DRCR"  When '.$d.' Then  "CLEARINGAMT"  Else 0 End "DRCLEARINGAMT" 
FROM 
( SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH","TRAN_ACTYPE" "TRAN_GLACTYPE", "TRAN_GLACNO", ACMASTER."AC_SUBSCODE","TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO", "TRAN_AMOUNT"
, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE"  , DAILYTRAN."TRAN_SOURCE_NO"  , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "TRAN_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "TRAN_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CLEARINGAMT" , '.$TRAN_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."TRAN_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" ,"TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH","TRAN_ACTYPE" "TRAN_GLACTYPE", "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO", "TRAN_AMOUNT" , "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" ,  HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "TRAN_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "TRAN_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "TRAN_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$TRAN_AMOUNT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON HISTORYTRAN."TRAN_GLACNO"= ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE","IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", "INTEREST_GLACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "INTEREST_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "INTEREST_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "INTEREST_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$INTEREST_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."INTEREST_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."INTEREST_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE",  "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", "INTEREST_GLACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "INTEREST_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "INTEREST_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "INTEREST_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "INTEREST_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$INTEREST_AMOUNT.' REF_FIELD  FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON HISTORYTRAN."INTEREST_GLACNO" = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
AND HISTORYTRAN."INTEREST_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("RECPAY_INT_GLACNO" AS INTEGER) "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "RECPAY_INT_AMOUNT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$RECPAY_INT_AMOUNT.' REF_FILED  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."RECPAY_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND           
 DAILYTRAN."RECPAY_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All   
  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("RECPAY_INT_GLACNO" AS INTEGER) "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "RECPAY_INT_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN "RECPAY_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$RECPAY_INT_AMOUNT.' REF_FILED  FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."RECPAY_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
  TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."RECPAY_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", 
"IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", "DD_COMMISSION_ACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "DD_COMMISSION_AMT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,DAILYTRAN."TRAN_SOURCE_NO" ,  DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CLEARINGAMT",'.$DD_COMMISSION_AMT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON DAILYTRAN."DD_COMMISSION_ACNO" = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
AND DAILYTRAN."DD_COMMISSION_AMT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", "DD_COMMISSION_ACNO" "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO" , "DD_COMMISSION_AMT" "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "DD_COMMISSION_AMT" ELSE 0 END,0),0)"TRANSFERAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CASHAMT" , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "DD_COMMISSION_AMT" ELSE 0 END,0) "CLEARINGAMT",'.$DD_COMMISSION_AMT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."DD_COMMISSION_ACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
 TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."DD_COMMISSION_AMT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", 
"PENAL_INT_GLACNO" AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , 
"PENAL_INT_AMOUNT" AS "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , 
DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$PENAL_INT_AMOUNT.' REF_FIELD  FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
AND  DAILYTRAN."PENAL_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", 
 "IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", 
 "PENAL_INT_GLACNO" AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  ,
 "PENAL_INT_AMOUNT" AS "TRAN_AMOUNT", "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", 
 HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , 
 HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  ,
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$PENAL_INT_AMOUNT.' REF_FIELD  
FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO" 
WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."PENAL_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", 
"IS_INTEREST_ENTRY", "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("REC_PENAL_INT_GLACNO" AS INTEGER) AS "TRAN_GLACNO", 
ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "REC_PENAL_INT_AMOUNT" AS TRAN_AMOUNT, "NARRATION", 
"TRAN_STATUS", 1 "RECCOUNTER", DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , 
DAILYTRAN."TRAN_SOURCE_TYPE", DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0)  
+ COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  ,
COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$REC_PENAL_INT_AMOUNT.' REF_FIELD  
FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."REC_PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  
WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= 
TO_DATE('.$edate.','.$datefandmate.')   AND  DAILYTRAN."REC_PENAL_INT_AMOUNT" > 0  AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("REC_PENAL_INT_GLACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "REC_PENAL_INT_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO", HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"  , COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0)  + COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "REC_PENAL_INT_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CASHAMT"  , COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "REC_PENAL_INT_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$REC_PENAL_INT_AMOUNT.' REF_FIELD  FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."REC_PENAL_INT_GLACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= 
TO_DATE('.$edate.','.$datefandmate.')  AND HISTORYTRAN."REC_PENAL_INT_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER1_ACNO" AS INTEGER)  AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE",
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER1_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER1_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER1_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER1_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER1_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND  DAILYTRAN."OTHER1_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR","TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
  "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER1_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
  "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER1_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
  HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
  HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , 
  COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER1_AMOUNT" ELSE 0 END,0)  + 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER1_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
           COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER1_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER1_AMOUNT.' REF_FIELD  
           FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER1_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
           WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
           AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
  AND HISTORYTRAN."OTHER1_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER2_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER2_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER2_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER2_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER2_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER2_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND  DAILYTRAN."OTHER2_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER2_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER2_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE" , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER2_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER2_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER2_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER2_AMOUNT.' REF_FIELD  
          FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER2_ACNO" AS INTEGER) = ACMASTER."AC_NO" 
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER2_AMOUNT" > 0   AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER3_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER3_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER",
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"     , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER3_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER3_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER3_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER3_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER3_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER3_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER3_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER3_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER3_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER3_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER3_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER3_ACNO" AS INTEGER) = ACMASTER."AC_NO"  WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER3_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER4_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER4_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER4_AMOUNT" ELSE 0 END,0)  +
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER4_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER4_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER4_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER4_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER4_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER4_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" , 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE", HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER4_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER4_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT" , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CASHAMT" , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER4_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER4_AMOUNT.' REF_FIELD  
          FROM  HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER4_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER4_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER5_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER5_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" ,
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER5_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER5_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER5_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER5_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER5_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER5_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER5_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" , 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER5_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER5_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER5_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER5_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER5_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER5_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER6_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER6_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER" ,
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   ,
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER6_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER6_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER6_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER6_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.', '.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER6_AMOUNT" > 0 
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER6_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER6_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER6_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER6_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER6_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER6_AMOUNT.' REF_FIELD  
         FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER6_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
         AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
AND HISTORYTRAN."OTHER6_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER7_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER7_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
 DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER7_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER7_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER7_AMOUNT.' REF_FIELD  
          FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER7_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
          AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   AND DAILYTRAN."OTHER7_AMOUNT" > 0 
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER7_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER7_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,  
 HISTORYTRAN."TRAN_SOURCE_NO" ,HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER7_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER7_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER7_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER7_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER7_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.', '.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER7_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER8_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER8_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" ,DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER8_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER8_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER8_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER8_ACNO" AS INTEGER) = ACMASTER."AC_NO" 
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER8_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.'  "TRAN_GLACTYPE", CAST("OTHER8_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER8_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER",
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" ,
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER8_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER8_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER8_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER8_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER8_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER8_AMOUNT" > 0   AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER9_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE",
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER9_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" ,
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE"  , DAILYTRAN."AC_CLOSED"  ,
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER9_AMOUNT" ELSE 0 END,0)   + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER9_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CLEARINGAMT" ,'.$OTHER9_AMOUNT.' REF_FIELD 
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER9_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER9_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER9_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER9_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER9_AMOUNT" ELSE 0 END,0)   + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER9_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER9_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER9_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER9_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER9_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY",
"TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER10_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
"TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER10_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER10_AMOUNT" ELSE 0 END,0)  + 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER10_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
         COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER10_AMOUNT.' REF_FIELD  
         FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER10_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
         WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
         AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
         AND DAILYTRAN."OTHER10_AMOUNT" > 0  
AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER10_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER10_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , HISTORYTRAN."TRAN_SOURCE_TYPE" , 
 HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER10_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER10_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  ,
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER10_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER10_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER10_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  AND 
          CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER10_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All  
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER11_ACNO" AS INTEGER) AS "TRAN_GLACNO", ACMASTER."AC_SUBSCODE", 
 "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER11_AMOUNT" TRAN_AMOUNT, "NARRATION", "TRAN_STATUS", 1 "RECCOUNTER", 
 DAILYTRAN."USER_CODE", DAILYTRAN."OFFICER_CODE" , DAILYTRAN."DIVIDEND_ENTRY" , DAILYTRAN."TRAN_SOURCE_TYPE" , 
 DAILYTRAN."TRAN_SOURCE_NO" , DAILYTRAN."TRAN_ENTRY_TYPE" , DAILYTRAN."AC_CLOSED"   , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER11_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER11_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER11_AMOUNT.' REF_FIELD  
          FROM DAILYTRAN LEFT OUTER JOIN ACMASTER ON CAST(DAILYTRAN."OTHER11_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(DAILYTRAN."TRAN_DATE" AS DATE) >= TO_DATE('.$stdate.','.$datefandmate.')   
          AND CAST(DAILYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')   
          AND DAILYTRAN."OTHER11_AMOUNT" > 0  
 AND DAILYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
Union All 
 SELECT "TRAN_NO", "TRAN_DATE", "TRAN_TIME" , "TRAN_TYPE", "TRAN_MODE", "TRAN_DRCR", "TRAN_ACNOTYPE", "IS_INTEREST_ENTRY", 
 "TRAN_PROCESS_YEAR","TRAN_PROCESS_MONTH", '.$no.' "TRAN_GLACTYPE", CAST("OTHER11_ACNO" AS INTEGER) AS "TRAN_GLACNO", 
 ACMASTER."AC_SUBSCODE", "TRAN_ACTYPE", "TRAN_ACNO", "CHEQUE_NO"  , "OTHER11_AMOUNT" TRAN_AMOUNT, "NARRATION", 
 "TRAN_STATUS", 1 "RECCOUNTER", HISTORYTRAN."USER_CODE", HISTORYTRAN."OFFICER_CODE" , HISTORYTRAN."DIVIDEND_ENTRY" , 
 HISTORYTRAN."TRAN_SOURCE_TYPE" , HISTORYTRAN."TRAN_SOURCE_NO" , HISTORYTRAN."TRAN_ENTRY_TYPE"  , HISTORYTRAN."AC_CLOSED"  , 
 COALESCE(COALESCE(CASE "TRAN_TYPE" WHEN '.$tr.' THEN "OTHER11_AMOUNT" ELSE 0 END,0)  + 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$jv.' THEN "OTHER11_AMOUNT" ELSE 0 END,0),0)"TRANSFERAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cs.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CASHAMT"  , 
          COALESCE(CASE "TRAN_TYPE" WHEN '.$cl.' THEN  "OTHER11_AMOUNT" ELSE 0 END,0) "CLEARINGAMT",'.$OTHER11_AMOUNT.' REF_FIELD  
          FROM HISTORYTRAN LEFT OUTER JOIN ACMASTER ON CAST(HISTORYTRAN."OTHER11_ACNO" AS INTEGER) = ACMASTER."AC_NO"  
          WHERE CAST(HISTORYTRAN."TRAN_DATE" AS DATE)>= TO_DATE('.$stdate.','.$datefandmate.')  
          AND CAST(HISTORYTRAN."TRAN_DATE" AS DATE) <= TO_DATE('.$edate.','.$datefandmate.')  
 AND HISTORYTRAN."OTHER11_AMOUNT" > 0  AND HISTORYTRAN."TRAN_STATUS" = '.$TRAN_STATUS.'
) AS "VWTMPSUBSIDARYOTHER" 
  WHERE "DIVIDEND_ENTRY" <> false
  AND "TRAN_AMOUNT" <> 0  
  AND "AC_SUBSCODE" =2 ';

    //echo $query;   

$sql =  pg_query($conn,$query);
     
$i = 0;


while($row = pg_fetch_assoc($sql)){

$tmp=[
    'CRCASHAMT' => $row['CRCASHAMT'],
    'CRTRANSFERAMT' => $row['CRTRANSFERAMT'],
    'Total_amount' => $row['TRAN_AMOUNT'],
    'account_no'=> $row['TRAN_ACNO'],
    'Name' => $row['NARRATION'],
    'Checkno' => $row['CHEQUE_NO'],
    'DRCASHAMT' => $row['DRCASHAMT'],
    'DRTRANSFERAMT' => $row['DRTRANSFERAMT'],

    'total_amount_user' => $row['TRAN_AMOUNT'],
    
    
    'user' => $row['USER_CODE'],
    'officer' => $row['OFFICER_CODE'],
    'total_amount' => $row['TRAN_AMOUNT'],

    'stdate' => $stdate_,
    'edate' => $edate_,
    'branchName' => $branchName,
    'bankName' => $bankName1,
];
$data[$i]=$tmp;
$i++;

}
ob_end_clean();
$config = ['driver'=>'array','data'=>$data];

$report = new PHPJasperXML();
$report->load_xml_file($filename)    
->setDataSource($config)
->export('Pdf');

?>
